services:
  client:
    image: node:24-alpine
    command:
      - npx
      - --yes
      - screepers-steamless-client
      - --package
      - /screeps.nw
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --internal_backend
      - http://screeps:21025
    depends_on:
      screeps:
        condition: service_started
    volumes:
      - npm-cache:/root/.npm
      - ${SCREEPS_NW_PATH:?Missing SCREEPS_NW_PATH in .env}:/screeps.nw:ro
    ports:
      - 8080:8080/tcp
    restart: unless-stopped
  screeps:
    image: ghcr.io/jomik/screeps-server:edge
    volumes:
      - ./config.yml:/screeps/config.yml
      - screeps-data:/screeps
      - screeps-mods:/screeps/mods
    ports:
      - 21025:21025/tcp
    environment:
      MONGO_HOST: mongo
      REDIS_HOST: redis
      STEAM_KEY: ${STEAM_KEY:?"Missing steam key"}
    restart: unless-stopped

  curl:
    image: quay.io/curl/curl:latest
    network_mode: 'service:screeps'

  mongo:
    image: mongo:4.4.18
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  npm-cache:
  redis-data:
  mongo-data:
  screeps-data:
  screeps-mods:
